#
#
# Clear docker cache
# docker system prune --all
# docker volume prune
# docker login -u wilsonjunior
# dckr_pat_I11iPGMfegdN7cExkhKrjDP-piI
#
services:
  # Database - MYSQL
  # mysql:
  #   container_name: 3marias_database
  #   image: mysql:5.7
  #   ports:
  #     - "3306:3306"
  #   expose:
  #     - "3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=12345
  #     - MYSQL_ROOT_USER=user
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=12345
  #     - MYSQL_DATABASE=testdb

  # Backend - LARAVEL
  php:
    container_name: 3marias_app
    #image: wilsonjunior/busquei:1.3
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/3marias
    ports:
      - "80:80"
    #it must run on dev
    entrypoint: ["bash", "-c", "php artisan serve --port 80 --host 0.0.0.0"]
    #entrypoint: ["bash", "-c", "php composer.phar install && php artisan serve --port 80 --host 0.0.0.0"]
    
  # Frontend - React
  # react:
  #   container_name: 3marias_frontend
  #   build: ./3marias/public/application/
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./3marias/public/application:/usr/src/app/
  #   ports:
  #     - 80:80
  #   #it must run on dev 
  #   #entrypoint: ["bash", "-c", "PORT=80 npm start"]
  #   entrypoint: ["bash", "-c", "npm install && PORT=80 npm start"]
